colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = false
  showScrollToTop = true

[homepage]
  layout = "hero"
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/blog/"
  cardView = true
  cardViewScreenWidth = false

[article]
  showDate = true
  showAuthor = true
  showHero = true
  heroStyle = "basic"
  showBreadcrumbs = true
  showDraftLabel = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showTaxonomies = true
  showWordCount = false
  showRelatedContent = true
  relatedContentLimit = 3

[list]
  showHero = false
  showBreadcrumbs = true
  showSummary = true
  showCards = true
  cardView = true
  groupByYear = false
